
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 18;
  public static final int ELSE = 12;
  public static final int PLUS = 14;
  public static final int INT = 20;
  public static final int RBRACE = 7;
  public static final int RPAREN = 4;
  public static final int SEMI = 5;
  public static final int END = 13;
  public static final int IF = 11;
  public static final int LPAREN = 3;
  public static final int COLON = 10;
  public static final int LBRACE = 6;
  public static final int COMMA = 8;
  public static final int CMP = 22;
  public static final int EOF = 0;
  public static final int DIV = 17;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int ASSIGN = 19;
  public static final int MUL = 16;
  public static final int EQU = 9;
  public static final int VAR = 21;
  public static final int FUN = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUN",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "EQU",
  "COLON",
  "IF",
  "ELSE",
  "END",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "ASSIGN",
  "INT",
  "VAR",
  "CMP"
  };
}

